# Terra stablecoin project schema
# <https://terra.money/>

namespace = "core/StdTx"
acc_prefix = "terra"
val_prefix = "terravaloper"

#
# Oracle vote transactions
# <https://docs.terra.money/dev/spec-oracle.html>
#

# MsgAggregateExchangeRatePrevote
# (NOTE: presently undocumented. See example below)
# <https://finder.terra.money/columbus-4/tx/6E2E83CF8B2F287CDBFD6C3716A65F6D3235EAEF233198289688B2A65609A71A>
[[definition]]
type_name = "oracle/MsgAggregateExchangeRatePrevote"
fields = [
    { name = "hash",  type = "string" },
    { name = "feeder", type = "sdk.AccAddress" },
    { name = "validator", type = "sdk.ValAddress" },
]

# MsgAggregateExchangeRateVote
# (NOTE: presently undocumented. See example below)
# <https://finder.terra.money/columbus-4/tx/6E2E83CF8B2F287CDBFD6C3716A65F6D3235EAEF233198289688B2A65609A71A>
[[definition]]
type_name = "oracle/MsgAggregateExchangeRateVote"
fields = [
    { name = "salt", type = "string" },
    { name = "exchange_rates", type = "string"},
    { name = "feeder", type = "sdk.AccAddress" },
    { name = "validator", type = "sdk.ValAddress" },
]

# MsgExchangeRatePrevote
# <https://docs.terra.money/dev/spec-oracle.html#msgexchangerateprevote>
[[definition]]
type_name = "oracle/MsgExchangeRatePrevote"
fields = [
    { name = "hash",  type = "string" },
    { name = "denom", type = "string" },
    { name = "feeder", type = "sdk.AccAddress" },
    { name = "validator", type = "sdk.ValAddress" },
]

# MsgExchangeRateVote
# <https://docs.terra.money/dev/spec-oracle.html#msgexchangeratevote>
[[definition]]
type_name = "oracle/MsgExchangeRateVote"
fields = [
    { name = "exchange_rate", type = "sdk.Dec"},
    { name = "salt", type = "string" },
    { name = "denom", type = "string" },
    { name = "feeder", type = "sdk.AccAddress" },
    { name = "validator", type = "sdk.ValAddress" },
]
