# https://github.com/RustSec/cargo-audit/blob/master/audit.toml.example

[advisories]
ignore = [
    "RUSTSEC-2020-0016",
    "RUSTSEC-2020-0036",
    "RUSTSEC-2021-0073",
    "RUSTSEC-2021-0078",
    "RUSTSEC-2021-0079"
]
